version: '3.8'

services:
  ufc-api:
    build: .
    container_name: ufc-events-api
    ports:
      - "${API_EXTERNAL_PORT:-5010}:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=${FLASK_APP:-src/api.py}
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=${REDIS_HOST:-ufc-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - ufc-redis
    restart: unless-stopped

  ufc-redis:
    image: redis:alpine
    container_name: ufc-redis
    restart: unless-stopped
