version: '3.8'

services:
  ufc-api:
    build: .
    container_name: ufc-events-api
    ports:
      - "5010:5000"
    environment:
      - FLASK_APP=src/api.py
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
